# Generated by Django 5.2.7 on 2026-06-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_entreprise", models.CharField(max_length=255)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logo/")),
                ("devise", models.CharField(default="FCFA", max_length=10)),
            ],
        ),
    ]
