# Generated by Django 5.2.7 on 2026-06-07 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btp", "0002_systemsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="lignedevis",
            old_name="prix",
            new_name="prix_unitaire",
        ),
        migrations.RemoveField(
            model_name="devis",
            name="montant_total",
        ),
        migrations.AddField(
            model_name="devis",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="statut",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("envoye", "Envoyé"),
                    ("accepte", "Accepté"),
                    ("refuse", "Refusé"),
                ],
                default="brouillon",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="adresse",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="devis",
            name="date_creation",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="devis",
            name="projet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devis",
                to="btp.projet",
            ),
        ),
        migrations.AlterField(
            model_name="lignedevis",
            name="devis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="btp.devis",
            ),
        ),
        migrations.AlterField(
            model_name="lignedevis",
            name="quantite",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("agent", "Agent"),
                            ("commercial", "Commercial"),
                            ("conducteur", "Conducteur"),
                            ("responsable", "Responsable"),
                        ],
                        default="agent",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
