# Generated by Django 5.2.7 on 2026-06-11 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0003_rename_prix_lignedevis_prix_unitaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='projet',
            name='progression',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DocumentProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='projets/documents/')),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='btp.projet')),
            ],
        ),
    ]
